# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='name_text',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='studentnum_text',
            field=models.CharField(default='123', max_length=200),
            preserve_default=False,
        ),
    ]
